// eslint-disable-next-line import/no-anonymous-default-export
export default {
  plugins: ["@ianvs/prettier-plugin-sort-imports", "prettier-plugin-tailwindcss"],
  trailingComma: "es5",
  tabWidth: 2,
  printWidth: 120,
  semi: false,
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "^@/app/(.*)$",
    "^@/components/(.*)$",
    "^@/components/ui/(.*)$",
    "^@/config/(.*)$",
    "^@/constants/(.*)$",
    "^@/hooks/(.*)$",
    "^@/lib/(.*)$",
    "^@/server/(.*)$",
    "^@/styles/(.*)$",
    "^@/trpc/(.*)$",
    "^@/types/(.*)$",
    "^@/utils/(.*)$",
    "",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
}
